//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practical_Training_View.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodNeeded
    {
        public int Blood_ID { get; set; }
        public int Admin_ID { get; set; }
        public bool isNeed { get; set; }
        public string Blood_Name { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
